In [ ]:
# https://towardsdatascience.com/semantic-similarity-using-transformers-8f3cb5bf66d6

In [1]:
from sentence_transformers import SentenceTransformer, util
import numpy as np

In [2]:
model = SentenceTransformer('stsb-roberta-large')

In [3]:
sentence1 = "Bonjour, je fais du machine learning"
sentence2 = "Bonjour, je fais du café"

# encode sentences to get their embeddings
embedding1 = model.encode(sentence1, convert_to_tensor=True)
embedding2 = model.encode(sentence2, convert_to_tensor=True)

#compute similarity scores of two embeddings
cosine_scores = util.pytorch_cos_sim(embedding1, embedding2)

print("Sentence 1:", sentence1)
print("Sentence 2:", sentence2)
print("Similarity score:", cosine_scores.item())

Sentence 1: Bonjour, je fais du machine learning
Sentence 2: Bonjour, je fais du café
Similarity score: 0.6240372657775879


In [6]:
corpus = ["I like Python because I can build AI applications",
          "I like Python because I can do data analytics",
          "The cat sits on the ground",
         "The cat walks on the sidewalk"]

# encode corpus to get corpus embeddings
corpus_embeddings = model.encode(corpus, convert_to_tensor=True).cpu().numpy()

In [7]:
corpus_embeddings

array([[-0.46271363,  0.740684  , -0.26615492, ...,  1.6758345 ,
        -2.6872828 , -0.21768837],
       [-0.38600743,  0.6501623 , -0.30140665, ...,  1.5000771 ,
        -2.2584767 ,  0.7605825 ],
       [-0.23815393,  0.52042073, -0.2830665 , ...,  0.09840213,
        -0.5524518 ,  0.40428737],
       [ 0.4010999 , -0.8214358 , -0.03720642, ..., -0.2875635 ,
        -0.14245695, -0.13885774]], dtype=float32)

In [8]:
sentence = "I like Javascript because I can build web applications"

# encode sentence to get sentence embeddings
sentence_embedding = model.encode(sentence, convert_to_tensor=True).cpu().numpy()

In [9]:
# top_k results to return
top_k=2

# compute similarity scores of the sentence with the corpus
cos_scores = util.pytorch_cos_sim(sentence_embedding, corpus_embeddings)[0]



In [33]:
# Sort the results in decreasing order and get the first top_k
top_results = np.argpartition(cos_scores, 1)#, range(top_k))#[0:top_k]
top_results

tensor([3, 2, 1, 0])

In [44]:
#top_results = corpus_embeddings[]
[sentence_embedding[np.argsort(-cos_scores)]]

TypeError: only integer tensors of a single element can be converted to an index

In [34]:
print("Sentence:", sentence, "\n")
print("Top", top_k, "most similar sentences in corpus:")
for idx in top_results[0:top_k]:
    print(idx)
    print(corpus[idx], "(Score: %.4f)" % (cos_scores[idx]))

Sentence: I like Javascript because I can build web applications 

Top 2 most similar sentences in corpus:
tensor(3)
The cat walks on the sidewalk (Score: -0.0519)
tensor(2)
The cat sits on the ground (Score: 0.0806)


In [50]:
top_results

tensor([0, 1, 2, 3])

In [51]:
range(top_k)

range(0, 2)

In [53]:
-cos_scores

tensor([-0.6696, -0.5455, -0.0806,  0.0519])

In [58]:
x = [3, 4, 2, 1]
b = [2, 3]

[np.argpartition(x, b)]

[array([3, 2, 0, 1])]

In [60]:
x = [5,3, 4, 2, 1]
b = [3, 2]

[np.argpartition(x, b)]

[array([4, 3, 1, 2, 0])]